### PR TITLE
Arduino IDE 1.5+ compatibility

### PR DESCRIPTION
**Pull request by per1234**
Refomatted boards.txt and created the new hardware folder structure. The
old configuration file system is still in place for IDE version 1.0
compatibility.
Removed the Mega 1280 boards.txt entry because the bootloader file for
this board doesn't exist.

### CODE REVIEW

**Comment by LoathingKernel** [comment]
Everything seems to be in order. Thanks for the PR!

**Comment by Apollon77** [comment]
Hey, I still get the following error in current Arduino-IDE 1.6.5:
Could not find boards.txt in /Users/ingof/Dropbox/Arduino/hardware/ariadne/bootloaders. Is it pre-1.5?

**Comment by per1234** [comment]
@Apollon77 I just tested the current version of Ariadne with Arduino IDE 1.6.5r2 and it worked fine for me. That error doesn't make sense because the boards.txt location on 1.6.x is hardware/ariadne/avr/boards.txt. How did you install Ariadne? Did you follow the instructions [here](https://github.com/codebendercc/Ariadne-Bootloader)?

**Comment by Apollon77** [comment]
Yes. i doenloaded ZIP, unpacked and copied folder "hardware" into my sketch folder.
I can find two "Board.txt".
1.) .../hardware/ariadne/avr
2.) .../hardware/ariadne

In the folder .../hardware/ariadne/bootloader (where in subfolders all the Src files are in) is not such file and this is the warning about

**Comment by per1234** [comment]
The boards.txt in location 1 is for IDE 1.6.x, the boards.txt in location 2 is for IDE 1.0.x. By having them in both places it makes Ariadne compatible with all IDE versions. When do you get the 
> Could not find boards.txt in /Users/ingof/Dropbox/Arduino/hardware/ariadne/bootloaders. Is it pre-1.5?

error message(e.g. IDE startup, Burn Bootloader, Upload, Upload Using Programmer)?

**Comment by Apollon77** [comment]
I get this error when I call the "Board Manager" in the IDE. It seems that at this timepoint he searches "deeper" in the directories then before :-)

**Comment by per1234** [comment]
Ok, now I see exactly what is happening. The IDE interprets the hardware/ariadne/bootloaders folder as a separate architecture but then doesn't find a boards.txt so it throws a warning message. The avr architecture is being correctly recognized so Ariadne should work fine and the warning can be ignored and should have no other effects. If you find any problems using Ariadne let me know. Everything is working for me. This is an unfortunate side effect of the system I used to make a single installation of Ariadne compatible with all Arduino IDE versions but I still think it's better than the alternative of maintaining two branches.

**Pull request merged**
